export const TERRAIN_TILE_KEYS = [
  "grass_top",
  "grass_side",
  "dirt",
  "stone",
  "sand",
  "gravel",
  "snow",
  "lava",
  "log_side",
  "log_top",
  "planks",
  "cobblestone",
  "leaves",
  "water",
  "coal_ore",
  "iron_ore",
  "gold_ore",
  "diamond_ore",
  "torch",
  "lamp",
  "crafting_table",
  "furnace",
  "chest",
  "bed",
  "door",
  "composter",
  "lectern",
  "stonecutter",
  "farmland",
  "wheat_young",
  "wheat_mid",
  "wheat",
  "bell"
] as const;

export type TerrainTileKey = (typeof TERRAIN_TILE_KEYS)[number];
